name: Publish

on:
  release:
    types:
      - published

jobs:
  build:
    name: Execute project build
    runs-on: ubuntu-latest
    container: python:3.13-bookworm
    steps:
      - uses: actions/checkout@v4
      - run: pip install build
      - run: make build
      - name: Store build results
        uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: dist/
          if-no-files-found: error

  pypi_publish:
    name: Publish to PyPI
    needs: build
    permissions:
      # Required for PyPI trusted publishing
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve build results
        uses: actions/download-artifact@v4
        with:
          name: build-dist
          path: dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
